services:
  bankapi-clean-architecture:
    container_name: bankapi.Api
    image: ${DOCKER_REGISTRY-}bankapicleanarchitecture
    build:
      context: .
      dockerfile: BankApi-Clean-Architecture/Dockerfile
    depends_on:
      - bankapi.database
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
  bankapi.database:
    container_name: bankapi.database
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankapidb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
volumes:
  db_data: